services:
  - type: web
    name: pdf-transaction-extractor
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python wsgi.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: FLASK_HOST
        value: 0.0.0.0
      - key: FLASK_PORT
        value: 10000
      - key: UPLOAD_FOLDER
        value: uploads
      - key: TEMP_FOLDER
        value: temp
